### PR TITLE
Add a "host" parameter to add this value in share meta tag. Remove vi…

### PR DESCRIPTION
**Pull request by Guitouxx**
…deo information to hide these specific meta tags

### CODE REVIEW

**Comment by jhclaura** [comment]
Hello! thank you for the changes, I just tested locally, but couldn't get the api from the server.
Does it work for you on your end locally?

**Comment by Guitouxx** [comment]
Hello Laura,

Yes I can get the data from the server.
What errors do you have in the terminal when you try to retrieve the datas?

Guillaume TOMASI / Photographer
Montreal, QC / T. (+1) 514.581.4285
www.guillaumetomasi.com <http://www.guillaumetomasi.com/>

**Comment by jhclaura** [comment]
I run the server locally with `node server_sleep.js`, and when I go to localhost:6969, at the terminal I got "Error getting NFB Settings null", which is something I added when where's an error, at server_sleep.js line 44

Is it how you run the project locally too? Or is there anything I need to update?

Thanks!

**Comment by jhclaura** [comment]
Hi! I updated the changes to my demo site as well [sleep.jhclaura.com](http://sleep.jhclaura.com/), and got some errors as below

GET http://sleep.jhclaura.com/common/images/logo-ONF.svg 404 (Not Found) (index):17 
GET http://sleep.jhclaura.com/common/images/twitter.svg 404 (Not Found) (index):17
GET http://sleep.jhclaura.com/common/images/facebook-official.svg 404 (Not Found) (index):17 
Uncaught ReferenceError: ATTag is not defined
    at Framework.track (onf_framework.js:52)
    at Framework.showIntro (onf_framework.js:83)
    at new Framework (onf_framework.js:22)
    at (index):1094

Would you know why? Is there anything I need to change in settings.json file? Any guidance appreciated.
I'll notify the NFB to update the production site as well, will let you know if that works.

Thanks!

**Comment by Guitouxx** [comment]
Hi Laura,

These three errors is because NFB has installed a SSL Certificate on their main server and we have to use now some relative paths to include the images of the header. When you run your app on your server, you will not find these images because they don’t exist on your server. It will disappear when your app will publish on NFB server.

For your error about getting the datas from the api, it’s working online but not locally right? 


Guillaume TOMASI / Photographer
Montreal, QC / T. (+1) 514.581.4285
www.guillaumetomasi.com <http://www.guillaumetomasi.com/>

**Comment by jhclaura** [comment]
Yes correct, the error about getting the datas from the api only happens locally.
And thank you for the explanation, I understand it now. Does the `Uncaught ReferenceError: ATTag is not defined` also have the same reason?

I'll notify NFB to update the production site then, thank you very much!

**Comment by Guitouxx** [comment]
I think I will use the absolute path just to be sure everyone will localize the right assets and have the latest version.

Yes ATTag is for the same reason 

Guillaume TOMASI / Photographer
Montreal, QC / T. (+1) 514.581.4285
www.guillaumetomasi.com <http://www.guillaumetomasi.com/>

**Comment by jhclaura** [comment]
Hello Guillaume, again :)

Re the error when run locally, would you mind telling me a bit about how you do it successfully on your end? - how you modify the server script and settings.json?
I need to update the social sharing contents and images, and would like to test locally first before pushing to the production server, but couldn't make it to work yet.

Thank you!

**Comment by Guitouxx** [comment]
Hello Laura,

Before we can run locally with calling the dev api, but now I suppose ONF has disabled the CORS on their server.
So I call my local framework to get some simulated datas.

Maybe you can fork and install the git here https://bitbucket.org/Guitouxx/onf-veryveryshort <https://bitbucket.org/Guitouxx/onf-veryveryshort> locally (don’t forget to change external to true in the /demo/settings.json)

After that in your sever_sleep.js you can change the domain for the request (using the url you set to install the git)
Like that you will use a local api.

Does it make sense?

Guillaume TOMASI / Photographer
Montreal, QC / T. (+1) 514.581.4285
www.guillaumetomasi.com <http://www.guillaumetomasi.com/>

**Comment by jhclaura** [comment]
Thanks for the explain! Do I need to run anything for the framework? Or it is a static folder that I can just go to/request with url?

**Comment by Guitouxx** [comment]
Nop, normally everything is included inside.
Set a virtual host to access this folder locally via une url example http://onf <http://onf/> 

after that the url for the api will be http://onf/api/all <http://onf/api/all> 

Guillaume TOMASI / Photographer
Montreal, QC / T. (+1) 514.581.4285
www.guillaumetomasi.com <http://www.guillaumetomasi.com/>

**Comment by jhclaura** [comment]
Thanks. Below are my current steps but not working yet, would you mind take a quick look and see if there's anything wrong?

1. clone git, have a folder **onf-veryveryshort**
2. inside the folder **onf-veryveryshort**, I do `python -m SimpleHTTPServer 8080`
3. in my server_sleep.js, I chagne **apiHost** from `https://veryveryshort.nfb.ca/` to `http://localhost:8080/`
4. change my **settings.json** `"external": true,`

Thanks!

**Comment by Guitouxx** [comment]
Can you access http://localhost:8080 <http://localhost:8080/> and what do you see at http://localhost:8080/demo <http://localhost:8080/demo> and http://localhost:8080/api/app <http://localhost:8080/api/app> 

Guillaume TOMASI / Photographer
Montreal, QC / T. (+1) 514.581.4285
www.guillaumetomasi.com <http://www.guillaumetomasi.com/>

**Comment by jhclaura** [comment]
screen shot 2017-11-16 at 11 02 48 am

screen shot 2017-11-16 at 11 02 32 am

**Comment by Guitouxx** [comment]
Is the mod_rewriting is allowing in localhost:8080 ?
It could be that.



Guillaume TOMASI / Photographer
Montreal, QC / T. (+1) 514.581.4285
www.guillaumetomasi.com <http://www.guillaumetomasi.com/>

**Comment by jhclaura** [comment]
Ahh I don't know. Ok am going to try to drop the folder to a static site.

**Comment by jhclaura** [comment]
Hmm it seems it won't work by just upload somewhere but need to serve it.
Could you let me know how you set a virtual host to access this folder locally via an url?
Of if your framework is still up somewhere that I can request to?

**Comment by Guitouxx** [comment]
I’m using MAMP on MacOS. A little software to create virtual host.
If it’s just for add some sharing content in the settings.json, maybe it’s more easy to tell the NFB team to push new version to let you see the changes?
Guillaume TOMASI / Photographer
Montreal, QC / T. (+1) 514.581.4285
www.guillaumetomasi.com <http://www.guillaumetomasi.com/>

**Comment by jhclaura** [comment]
Yea I just did, but I also did something in the framework, for callback to not show my website until the landing screen of NFB is over, as below:

    var frameworkJS;
    if(hasInternet && '{% autoescape false %}{{ data.export_to_js }}{% endautoescape %}' != '')
    {
    	frameworkJS = new Framework('{% autoescape false %}{{ data.export_to_js }}{%endautoescape %}', monCallback);
    	// frameworkJS.track("test_de_statistique"); //exemple de tag
    }

    function monCallback()
    {
    	console.log("ok, now can start");
    	splashPage.style.opacity = 1;
    	aboutPage.style.opacity = 1;
    }

Would you mind let me know if this is alright, where I put the callback function, before I asked the IT guy there to push it to the production website.

Much appreciated!!

**Comment by jhclaura** [comment]
And this is based on what Martin suggested (but in php):
`var fW = new Framework('<?php echo $framework->exportToJS(); ?>’, monCallback);`

Please let me know when you have a second, thank you!

**Comment by Guitouxx** [comment]
Seems good Julia :)

Guillaume TOMASI / Photographer
Montreal, QC / T. (+1) 514.581.4285
www.guillaumetomasi.com <http://www.guillaumetomasi.com/>

**Comment by jhclaura** [comment]
Thank you!

**Comment by jhclaura** [comment]
Hello Guillaume, hope you are well :)

I was trying to access the framework locally again but bumped into some errors.
Hope you can shed some lights on it if you can! Below are my steps of attempt.

First, I updated **onf-veryveryshort** to V1.5 and served it with **MAMP**, by setting the **Document Root** to the **onf-veryveryshort** folder. It seems to be working because the demo works on http://localhost:8888/demo/ with ONF header

Secondly, on my **server** script, I changed
`apiHost = "https://veryveryshort.nfb.ca/";`
to
`apiHost = "http://localhost:8888/";`

Thirdly, on **settings.json**, I changed
`"external": true,`

Then on my local index.html, the arte header showed up (not like the demo is ONF header, do you know why?), but got some errors as below
`(index):17 Uncaught ReferenceError: ATInternet is not defined`
`(index):1105 Uncaught ReferenceError: Framework is not defined`

It seems I only got partial dependencies from the framework. Is there anything needed to be updated on the **server** script? I logged the response body, and below are the dependencies part:
```
[ '<link rel=\'stylesheet\' href=\'\' />',
  '<link rel=\'stylesheet\' href=\'\' />',
  '<script src=\'https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\'></script>',
  '<script>window.jQuery || document.write("<script src=\'\'><\\/script>")</script>',
  '<script src=\'\'></script>',
  '<script type=\'text/javascript\' src=\'https://www.arte.tv/components/bundles/Header.min.js\'></script>',
  '<script type=\'text/javascript\' src=\'https://static-cdn.arte.tv/static/styleguide/2.7.1/bundles/Footer.min.js\'></script>',
  '<script src=\'\'></script>',
  '<script src=\'\'></script>',
  '<script src=\'\'></script>' ],
```

Would you know any possible reasons for this?
Please let me know your thoughts, any suggestions would be appreciated.
Thank you!

**Comment by Guitouxx** [comment]
Hello Laura,
I’m fine thank yo. what about you?

Regarding the header, when you call the api to get the geoloc, you send the ip adress to tell the framework where is your position. But in localhost , the req.ip wil return someting empty or :::1 and I suppose the framework will return the hardcoded geoloc 

$this->detection = (object) [
"language" => "en",
"languages" => ["en", "fr", "de"],
"topnav" => "arte",
"environment" => "dev",
"domain" => "https://".str_replace("www.", "", preg_replace("/\/(.+)/", "", $_SERVER["SERVER_NAME"])),
"framework_domain" => "https://veryveryshort.nfb.ca"
];


For the both errors you have, yes you have a fragmented json response, your index.page didn’t find all files ('<script src=\'\'></script>’)
What do you have on geoloc object for the framework_domain value? Usually you will have https://veryveryshort.nfb.ca <https://veryveryshort.nfb.ca/> 

Is that your case?
Thanks
 

Guillaume TOMASI / Photographer
Montreal, QC / T. (+1) 514.581.4285
www.guillaumetomasi.com <http://www.guillaumetomasi.com/>

**Comment by Guitouxx** [comment]
Hello again,

I thought about it and I suppose I know what is going on.
Now, we changed something for the external = true. It’s used by the project hosted by Arte and when it’s set to true, the framework call a dedicated method to get the right geoloc from the ONF (becaus the project from Arte are hosted in Europe, but they use PHP..)
So they have to call another php method, but you can’t because you run your app with Nodejs.

Maybe you can change something in your onf_framework.php file
You have this fragment of code


You can update it to that thing



But because you call the api on your localhost, it won’t show you the right header :(

Guillaume TOMASI / Photographer
Montreal, QC / T. (+1) 514.581.4285
www.guillaumetomasi.com <http://www.guillaumetomasi.com/>

**Pull request merged**
